# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ValidResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('start_date', models.DateTimeField(default='2018-01-01')),
                ('end_date', models.DateTimeField(default='2018-01-31')),
                ('mse', models.DecimalField(decimal_places=4, max_digits=20)),
                ('mabs', models.DecimalField(decimal_places=4, max_digits=20)),
                ('energy', models.DecimalField(decimal_places=4, max_digits=4)),
                ('acc', models.DecimalField(decimal_places=4, max_digits=4)),
                ('precision', models.DecimalField(decimal_places=4, max_digits=4)),
                ('recall', models.DecimalField(decimal_places=4, max_digits=4)),
                ('learniing_type', models.CharField(choices=[('SUPER', 'Supervised Learning'), ('SEMi', 'Semi-Supervised Learning'), ('MULTI', 'Multi-Tasks Learning')], default='SUPER', max_length=30)),
            ],
        ),
    ]
