# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_validresult_appliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validresult',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='validresult',
            name='start_date',
        ),
    ]
