# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_auto_20180614_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='validresult',
            name='end_date',
            field=models.DateTimeField(default=datetime.date),
        ),
        migrations.AddField(
            model_name='validresult',
            name='start_date',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
