# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0007_auto_20180614_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validresult',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='validresult',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
