# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0012_auto_20180614_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validresult',
            name='start_date',
        ),
    ]
