# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0013_remove_validresult_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validresult',
            name='end_date',
        ),
        migrations.AddField(
            model_name='validresult',
            name='date',
            field=models.CharField(default='2018-01-01', max_length=50, verbose_name='Date'),
        ),
    ]
